
esphome:
  name: weather_station
  comment: "Misol RS485 Weather station"

esp32:
  board: esp32dev
    
logger:
  level: DEBUG

uart:
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1

external_components:
  source:
    type: local
    path: ./components
  components: [ misol_weather ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome

web_server:

misol_weather:

sensor:
  - platform: misol_weather
    temperature:
      name: ${device_name} Temperature
    humidity:
      name: ${device_name} Humidity
    pressure:
      name: ${device_name} Pressure
    wind_speed:
      name: ${device_name} Wind Speed
    wind_direction_degrees:
      name: ${device_name} Wind Direction
    wind_gust:
      name: ${device_name} Wind Gust
    rainfall:
      name: ${device_name} Rainfall
    light:
      name: ${device_name} Light