substitutions:
  device_name: Weather station

esphome:
  name: weather_station
  comment: "Misol RS485 Weather station"

esp32:
  board: esp32dev
    
logger:
  level: DEBUG

uart:
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1

external_components:
  source:
    type: local
    path: ./components
  components: [ misol_weather ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome

web_server:

misol_weather:

sensor:
  - platform: misol_weather
    temperature:
      name: ${device_name} Temperature
    humidity:
      name: ${device_name} Humidity
    pressure:
      name: ${device_name} Pressure
    wind_speed:
      name: ${device_name} Wind Speed
    wind_direction_degrees:
      name: ${device_name} Wind Direction
    wind_gust:
      name: ${device_name} Wind Gust
    accumulated_precipitation:
      name: ${device_name} Accumulated Precipitation 
    light:
      name: ${device_name} Light
    uv_intensity:
      name: ${device_name} Ultraviolet Intensity
    uv_index:
      name: ${device_name} Ultraviolet Index
    precipitation_intensity:
      name: ${device_name} Precipitation Intensity

binary_sensor:
  - platform: misol_weather
    battery_level:
      name: ${device_name} Battery Level
    night:
      name: ${device_name} Night
      threshold:
        upper: 5.5
        lower: 4.5

packages:
  wind_direction_text: !include configs/text_sensor/wind_direction.yaml
  wind_speed_text: !include configs/text_sensor/wind_speed.yaml
  light_intensity_text: !include configs/text_sensor/light_intensity.yaml
  precipitation_intensity_text: !include configs/text_sensor/precipitation_intensity.yaml
  weather_conditions_text: !include configs/text_sensor/weather_conditions.yaml
