substitutions:
  device_name: Weather station
  device_id: weather_station
  uart_id: weather_port
  device_description: "Weather station"

esphome:
  name: weather_station
  comment: "${device_description}"

esp32:
  board: esp32dev
    
logger:
  level: DEBUG

uart:
  id: ${uart_id}
  rx_pin: GPIO5
  baud_rate: 9600
  stop_bits: 1
#  debug:
#    direction: BOTH
#    dummy_receiver: true
#    sequence:
#      - lambda: >-
#          UARTDebug::log_hex(uart::UART_DIRECTION_RX, bytes, ' ');
#          float temperature = (bytes[4] + (((uint16_t)bytes[3] & 0x07) << 8)) - 400;
#          ESP_LOGD("WS", "    Temeperature: %.1f", temperature / 10);
#          ESP_LOGD("WS", "    Humidity: %d", bytes[5]);
  
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO0_IN
#  phy_addr: 1
#  power_pin: GPIO16

external_components:
  source:
    type: local
    path: ./components
  components: [ misol_weather ]

misol_weather:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:

sensor:
  - platform: uptime
    name: ${device_name} uptime
    entity_category: diagnostic
    unit_of_measurement: "Hrs"
    accuracy_decimals: 2
    state_class: total_increasing
    filters:
      - lambda: return x/3660.0;
  - platform: template
    name: ${device_name} CPU temperature
    entity_category: diagnostic
    unit_of_measurement: °C
    accuracy_decimals: 2
    lambda: return temperatureRead();
    update_interval: 60s
    state_class: measurement


text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version
    hide_timestamp: true

switch:
  - platform: restart
    id: ${device_id}_board_restart
    name: ${device_name} restart
    entity_category: diagnostic

time:
  - platform: sntp
    id: ${device_id}_time
    timezone: 'Europe/Amsterdam'
    servers:
     - 0.192.168.10.100
    on_time:
      - seconds: 00
        minutes: 00
        hours: 3
        then:
          - switch.toggle: ${device_id}_board_restart
