
esphome:
  name: weather_station
  comment: "Misol RS485 Weather station"

esp32:
  board: esp32dev
    
logger:
  level: DEBUG

uart:
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1

external_components:
  source:
    type: local
    path: ./components
  components: [ misol_weather ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome

web_server:

misol_weather:

sensor:
  - platform: misol_weather
    temperature:
      name: Weather station Temperature
    humidity:
      name: Weather station Humidity
    pressure:
      name: Weather station Pressure
    wind_speed:
      name: Weather station Wind Speed
    wind_direction_degrees:
      name: Weather station Wind Direction
    wind_gust:
      name: Weather station Wind Gust
    accumulated_precipitation:
      name: Weather station Accumulated Precipitation 
    light:
      name: Weather station Light
    uv_intensity:
      name: Weather station Ultraviolet Intensity
    uv_index:
      name: Weather station Ultraviolet Index

binary_sensor:
  - platform: misol_weather
    battery_level:
      name: Weather station Battery Level

text_sensor:
  - platform: misol_weather
    wind_direction:
      name: Weather station Wind Direction Text
    wind_speed:
      name: Weather station Wind Speed Text
