# Text sensor for wind speed
# Depend on the wind speed sensor from the misol_weather integration
text_sensor:
  - platform: template
    name: "${device_name} Wind Speed Text"
    id: ${device_id}_wind_speed_text
    icon: "mdi:weather-windy"
    update_interval: 20s
    lambda: |-
      if (id(${device_id}_wind_speed).has_state()) {
        float wind_speed = id(${device_id}_wind_speed).state;
        if (wind_speed < 0.5) {
          return { "Calm" };
        } else if (wind_speed < 1.5) {
          return { "Light air" };
        } else if (wind_speed < 3.3) {
          return { "Light breeze" };
        } else if (wind_speed < 5.5) {
          return { "Gentle breeze" };
        } else if (wind_speed < 7.9) {
          return { "Moderate breeze" };
        } else if (wind_speed < 10.7) {
          return { "Fresh breeze" };
        } else if (wind_speed < 13.8) {
          return { "Strong breeze" };
        } else if (wind_speed < 17.1) {
          return { "Moderate gale" };
        } else if (wind_speed < 20.7) {
          return { "Fresh gale" };
        } else if (wind_speed < 24.4) {
          return { "Strong gale" };
        } else if (wind_speed < 28.4) {
          return { "Whole gale" };
        } else if (wind_speed < 32.6) {
          return { "Storm" };
        } else {
          return { "Hurricane" };
        }
      } else {
        return { "Unknown" };
      }
